asset-package:
    class: hiqdev\assetpackagist\console\AssetPackageController
bower-package:
    class: hiqdev\assetpackagist\console\BowerPackageController
queue:
    class: hiqdev\assetpackagist\console\QueueController

install:
    after:
        - create-storage
        - chmod-storage
        - migrate/up

create-storage:
    class:      directory
    path:       '@storage'
    lock:
        once:       true
        template:   empty
        chmod:      '0664'
    lastid:
        once:       true
        template:   empty
        chmod:      '0664'
    packages.json:
        once:       true
        template:   empty
        chmod:      '0664'
    p:
        chmod:      '0775'

clean-storage:
    class:      command
    path:       '@storage'
    sudo:       true
    command:    rm -rf lock lastid packages.json p

chmod-storage:
    class:      command
    path:       '@storage'
    sudo:       true
    commands:   |
       chown -R www-data lock lastid packages.json p
       chmod -R g+w,o-w lock lastid packages.json p
