deploy:
    after:
        - asset-storage/create
        - asset-storage/chmod
        - migrate/up

asset-storage:
    create:
        class:      directory
        path:       '@storage'
        lock:
            once:       true
            template:   empty
            chmod:      '0664'
        lastid:
            once:       true
            template:   empty
            chmod:      '0664'
        packages.json:
            once:       true
            template:   empty
            chmod:      '0664'
        p:
            chmod:      '0775'

    clean:
        class:      command
        path:       '@storage'
        sudo:       true
        command:    rm -rf lock lastid packages.json p

    chmod:
        class:      command
        path:       '@storage'
        sudo:       true
        commands:   |
           chown -R www-data lock lastid packages.json p
           chmod -R g+w,o-w lock lastid packages.json p
