package:
    name:           asset-packagist.hiqdev.com
    namespace:      hiqdev\assetpackagist

yii2webapp:
    ssl:            true
    sslPath:        crt/asset-packagist.hiqdev.com

config: src/config/console.php

do:
    class: hiqdev\assetpackagist\controllers\DoController

require:
    hiqdev/hidev-php:           "*"
    hiqdev/hidev-yii2-web-app:  "*@dev"
    hiqdev/hidev-vendor:        "*"
