package:
    type:           yii2-extension
    name:           asset-packagist
    title:          Asset Packagist
    keywords:       composer, bower, npm, asset, packagist
    namespace:      hiqdev\assetpackagist
    description:    |
        ![Composer](https://raw.githubusercontent.com/hiqdev/asset-packagist/master/docs/logo/asset-packagist.png)

        **Composer + Bower + NPM = friends forever!**

        This package is the core part of https://asset-packagist.org/ project.

        Asset Packagist allows installation of Bower and NPM packages as native
        Composer packages.

        **NO** plugins and **NO** Node.js are required.
